name: Haskell CI

env:
  ghc_version: 9.2.5
  cabal_version: 3.6.2.0

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ env.ghc_version }}
        cabal-version: ${{ env.cabal_version }}

    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/.cabal
        key: cabal-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: cabal-
    - name: Install formatters
      run: |
        cabal update
        cabal install --overwrite-policy=always cabal-fmt stylish-haskell
        echo "$HOME/.cabal/bin" >> $GITHUB_PATH
    - name: Check format
      run: |
        make fmt
        if [[ -z "$(git status --porcelain)" ]]; then
            echo "No non-formatted file."
        else
            echo "Non-formatted files:"
            git --no-pager diff
            exit 1
        fi
    - name: Build
      run: |
        cabal update
        cabal build
    - name: Run tests
      run: cabal test all
